"""
progenax - Differentiable initial conditions for N-body simulations.

Part of the jaxstro ecosystem.
"""

# Configure JAX for 64-bit precision BEFORE any other imports
# This must be called before any JAX arrays are created
from jaxstro.jaxconfig import enable_high_precision as _enable_jax_hp

_enable_jax_hp()
del _enable_jax_hp  # avoid leaking into public API

from .analytical import (
    SOLAR_SYSTEM_PLANETS,
    AnalyticalIC,
    earth_sun_2body,
    earth_sun_eccentric,
    figure_eight_period,
    get_planet,
    harmonic_oscillator,
    harmonic_solution,
    solar_system_full,
    solar_system_inner_4,
    sun_earth_jupiter_3body,
    three_body_figure_eight,
    two_body_energy,
    two_body_kepler,
    two_body_period,
)
from .binaries import (
    BinaryEnergyBudget,
    BinaryOrbitalState,
    BinaryState,
    CartesianState,
    CombinedBinaryFraction,
    CompanionElements,
    IndependentCompanions,
    KeplerElements,
    LogisticThermalEccentricity,
    LogNormalPeriod,
    LogUniformPeriod,
    MassDependentBinaryConfig,
    MoeCompanions,
    MoeEccentricity,
    RadialBinaryFraction,
    ResolvedBinaries,
    SanaOBPeriod,
    ThermalEccentricity,
    UniformEccentricity,
    batch_elements_to_resolved,
    binary_energy_budget,
    compute_period,
    find_bound_multiples,
    find_bound_pairs,
    period_to_semimajor_axis,
    primordial_survival,
    relative_energy,
    resolve_binary_components,
    sample_isotropic_orientations,
    sample_mass_dependent_orbits,
)
from .builders import (
    ICResult,
    Stars,
    Systems,
    TotalMass,
    build_binary_cluster,
    build_spatial_ic,
    compute_kinetic_energy,
    compute_potential_energy,
    compute_stellar_radii,
    to_com_frame,
    virial_scale,
)
from .builders_cluster import (
    ClusterParams,
    RotationSpec,
    build_cluster,
    build_cluster_from_params,
    build_eff_cluster,
    build_king_cluster,
    build_limepy_cluster,
    build_michie_cluster,
    build_plummer_cluster,
    matched_velocity_df,
)
from .cluster import MultiComponentCluster, energy_sorted_segregation
from .defaults import DEFAULT_UNITS

# IMF / binary statistics (audit R7: documented but not previously root-exported)
from .imf import (
    BinaryIMF,
    ChabrierIMF,
    ConstantBinaryFraction,
    FlatMassRatio,
    Maschberger,
    MassDependentBinaryFraction,
    MoeDiStefano2017,
    MoeDiStefano2017Full,
    MoeJointOrbit,
    MoePeriod,
    PowerLawIMF,
    PowerLawMassRatio,
    TruncatedIMF,
    TwinPeakedMassRatio,
)
from .kinematics import (
    EFFVelocityDF,
    KingVelocityDF,
    LIMEPYVelocityDF,
    MichieVelocityDF,
    PlummerVelocityDF,
    apply_differential_rotation,
    apply_solid_body_rotation,
    df_moment_dispersion,
    jeans_dispersion,
    project_dispersion,
)
from .profiles import (
    EFFProfile,
    KingProfile,
    LIMEPYProfile,
    MichieProfile,
    PlummerProfile,
    UniformSphereProfile,
    find_alpha_for_masses,
    solve_king_profile,
    solve_limepy_profile,
    solve_michie_profile,
    solve_multimass_limepy,
)
from .protocols import (
    BinaryFractionModel,
    CompanionModel,
    ConditionalEccentricityDistribution,
    EccentricityDistribution,
    IMFProtocol,
    MassPeriodEccentricityDistribution,
    PeriodDistribution,
    SpatialProfile,
    VelocityDF,
)
from .stellar import (
    inverse_zams_luminosity,
    zams_effective_temperature,
    zams_luminosity,
    zams_radius,
    zams_surface_gravity,
)
from .tidal import (
    apply_tidal_truncation,
    fill_factor_to_r_h,
    jacobi_radius,
    jacobi_radius_isothermal,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_UNITS",
    # Protocols
    "SpatialProfile",
    "VelocityDF",
    "IMFProtocol",
    "PeriodDistribution",
    "EccentricityDistribution",
    "ConditionalEccentricityDistribution",
    "MassPeriodEccentricityDistribution",
    "BinaryFractionModel",
    "CompanionModel",
    # Spatial density profiles
    "PlummerProfile",
    "KingProfile",
    "MichieProfile",
    "EFFProfile",
    "LIMEPYProfile",
    "UniformSphereProfile",
    "MultiComponentCluster",
    "solve_king_profile",
    "solve_michie_profile",
    "solve_limepy_profile",
    "solve_multimass_limepy",
    "find_alpha_for_masses",
    # IMF / binary statistics
    "PowerLawIMF",
    "ChabrierIMF",
    "Maschberger",
    "TruncatedIMF",
    "BinaryIMF",
    "FlatMassRatio",
    "PowerLawMassRatio",
    "TwinPeakedMassRatio",
    "MoeDiStefano2017",
    "MoeDiStefano2017Full",
    "MoePeriod",
    "MoeJointOrbit",
    "ConstantBinaryFraction",
    "MassDependentBinaryFraction",
    # Velocity distribution functions
    "PlummerVelocityDF",
    "KingVelocityDF",
    "MichieVelocityDF",
    "LIMEPYVelocityDF",
    "EFFVelocityDF",
    # Rotation overlays (audited entry points; previously not root-exported)
    "apply_solid_body_rotation",
    "apply_differential_rotation",
    # Dispersion forward models (3-D Jeans + B&M82 projection)
    "jeans_dispersion",
    "project_dispersion",
    "df_moment_dispersion",
    # Builders
    "ICResult",
    "Systems",
    "Stars",
    "TotalMass",
    "build_spatial_ic",
    "build_binary_cluster",
    "resolve_binary_components",
    "ResolvedBinaries",
    "CompanionElements",
    "IndependentCompanions",
    "MoeCompanions",
    "relative_energy",
    "find_bound_pairs",
    "find_bound_multiples",
    "primordial_survival",
    "BinaryEnergyBudget",
    "binary_energy_budget",
    "to_com_frame",
    "virial_scale",
    "compute_stellar_radii",
    "compute_kinetic_energy",
    "compute_potential_energy",
    # ZAMS stellar relations (Tout+1996; photometric, distinct from collision radii)
    "zams_luminosity",
    "zams_radius",
    "zams_effective_temperature",
    "zams_surface_gravity",
    "inverse_zams_luminosity",
    # Cluster convenience builders
    "build_cluster",
    "matched_velocity_df",
    "RotationSpec",
    "ClusterParams",
    "build_cluster_from_params",
    "build_plummer_cluster",
    "build_king_cluster",
    "build_eff_cluster",
    "build_michie_cluster",
    "build_limepy_cluster",
    # Analytical test cases
    "AnalyticalIC",
    "SOLAR_SYSTEM_PLANETS",
    "get_planet",
    "two_body_kepler",
    "two_body_period",
    "two_body_energy",
    "three_body_figure_eight",
    "figure_eight_period",
    "harmonic_oscillator",
    "harmonic_solution",
    "earth_sun_2body",
    "earth_sun_eccentric",
    "sun_earth_jupiter_3body",
    "solar_system_inner_4",
    "solar_system_full",
    # Binary orbital mechanics
    "KeplerElements",
    "CartesianState",
    "BinaryState",
    "compute_period",
    "period_to_semimajor_axis",
    "BinaryOrbitalState",
    "batch_elements_to_resolved",
    # Binary population distributions
    "LogUniformPeriod",
    "LogNormalPeriod",
    "SanaOBPeriod",
    "ThermalEccentricity",
    "UniformEccentricity",
    "LogisticThermalEccentricity",
    "MoeEccentricity",
    "sample_isotropic_orientations",
    "RadialBinaryFraction",
    "CombinedBinaryFraction",
    "MassDependentBinaryConfig",
    "sample_mass_dependent_orbits",
    # Tidal physics
    "jacobi_radius",
    "jacobi_radius_isothermal",
    "apply_tidal_truncation",
    "fill_factor_to_r_h",
    # Primordial (non-equilibrium) mass segregation
    "energy_sorted_segregation",
]
