"""Parity vs the canonical published LIMEPY (Gieles & Zocchi 2015 numpy/scipy code).

Engine A (`MultiComponentCluster` / `find_alpha_for_masses`) is asserted to be a
FAITHFUL reimplementation of the reference at ref-repos/limepy (git ef2a479):
same alpha_j, density shapes rho_j(r)/rho_j(0), dispersion shapes
sigma_j(r)/sigma_j(0), concentration log10(rt/r0), and rh/r0, at the gates
frozen from the measured 2026-06-11 parity table (scripts/
validate_limepy_reference.py; measured deviations 5e-7..1.5e-4, gates ~3-10x
that, all <=5e-4 -- 20x below the 1% physics target).

The reference CANNOT run in the project env (scipy>=1.17 breaks it), so this
test compares against the CACHED reference outputs committed at
``validation/data/limepy_reference/*.npz`` (generated by the pinned-subprocess
worker; provenance embedded in each npz). It NEVER shells out: if a cache file
is absent the test skips. Regenerate with::

    env -u VIRTUAL_ENV uv run --no-sync python scripts/validate_limepy_reference.py --regen
"""

import os

import jax
import jax.numpy as jnp
import numpy as np
import pytest

from progenax.cluster.multicomponent import MultiComponentCluster
from progenax.profiles.limepy import _aniso_density_scalar, limepy_density_hat
from progenax.profiles.limepy_multimass import (
    _aniso_v2hat_scalar,
    find_alpha_for_masses,
)

pytestmark = pytest.mark.slow  # each case is a hi-res (n_ode>=6000) coupled solve

CACHE_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..",
    "validation", "data", "limepy_reference")

# name -> (config, gates); mirrors scripts/validate_limepy_reference.py CONFIGS
# (the IMF config needs the binning at collection time, so the test covers the
# single-mass sanity corner + the two-component iso + aniso multimass cases).
CASES = {
    "single_g1": dict(
        W0=5.0, g=1.0, mj=None, Mj=None, delta=None, eta=None, ra=None,
        xi_max=30.0, n_ode=8000,
        gates=dict(rho=2e-5, sig=2e-5, alpha=1e-8, c=5e-4, rh=1e-4)),
    "twocomp_iso": dict(
        W0=5.0, g=1.0, mj=[0.3, 1.0], Mj=[0.7, 0.3], delta=0.5, eta=None,
        ra=None, xi_max=30.0, n_ode=8000,
        gates=dict(rho=5e-5, sig=3e-4, alpha=5e-4, c=5e-4, rh=1e-4)),
    "twocomp_ra_eta05": dict(
        W0=5.0, g=1.0, mj=[0.3, 1.0], Mj=[0.7, 0.3], delta=0.5, eta=0.5,
        ra=5.0, xi_max=30.0, n_ode=6000,
        gates=dict(rho=5e-5, sig=3e-4, alpha=5e-4, c=5e-4, rh=1e-4)),
}


def _load_reference(name):
    path = os.path.join(CACHE_DIR, f"{name}.npz")
    if not os.path.exists(path):
        pytest.skip(f"reference-LIMEPY cache absent: {path} "
                    "(run scripts/validate_limepy_reference.py --regen)")
    return np.load(path)


def _build_ours(cfg):
    if cfg["mj"] is None:
        return MultiComponentCluster.from_components(
            alpha_j=jnp.array([1.0]), w_j=jnp.array([1.0]), m_j=jnp.array([1.0]),
            W0=cfg["W0"], g=cfg["g"], xi_max=cfg["xi_max"],
            n_ode_points=cfg["n_ode"])
    m_j, M_j = jnp.asarray(cfg["mj"]), jnp.asarray(cfg["Mj"])
    eta = cfg["eta"] if cfg["eta"] is not None else 0.0
    alpha_j, _ = find_alpha_for_masses(
        m_j, M_j, cfg["W0"], cfg["g"], cfg["delta"], xi_max=cfg["xi_max"],
        n_points=cfg["n_ode"], ra_hat=cfg["ra"], eta=eta)
    return MultiComponentCluster.from_mass_segregation(
        alpha_j=alpha_j, m_j=m_j, W0=cfg["W0"], g=cfg["g"], delta=cfg["delta"],
        r_a=cfg["ra"], eta=eta, r_c=1.0, xi_max=cfg["xi_max"],
        n_ode_points=cfg["n_ode"])


def _ours_profiles(model, xi):
    """Centre-normalized (rho_hat_j, sigma_hat_j) on xi = r/r0 via the exact
    quadrature oracle at the solved psi (the sigma_j oracle of
    test_multimass_equilibrium_physics, in v2hat = I2/I0 form)."""
    psi = jnp.interp(xi, model.xi_grid, model.psi_grid, left=model.W0, right=0.0)
    rescale, ra_j = model.rescale_j, model.ra_hat_j
    rho, sig = [], []
    for j in range(rescale.shape[0]):
        p = jnp.where(jnp.isfinite(ra_j[j]), xi / ra_j[j], 0.0)
        if bool(jnp.isfinite(ra_j[j])):
            rho_j = jax.vmap(lambda W, pp: _aniso_density_scalar(W, pp, model.g))(
                rescale[j] * psi, p)
            rho_0 = _aniso_density_scalar(rescale[j] * model.W0, jnp.asarray(0.0),
                                          model.g)
        else:
            rho_j = limepy_density_hat(rescale[j] * psi, model.g)
            rho_0 = limepy_density_hat(rescale[j] * model.W0, model.g)
        v2_j = jax.vmap(lambda W, pp: _aniso_v2hat_scalar(W, pp, model.g))(
            rescale[j] * psi, p)
        v2_0 = _aniso_v2hat_scalar(rescale[j] * model.W0, jnp.asarray(0.0),
                                   model.g)
        rho.append(rho_j / rho_0)
        sig.append(jnp.sqrt(v2_j / v2_0))
    return jnp.stack(rho), jnp.stack(sig)


@pytest.mark.parametrize("name", sorted(CASES))
def test_parity_with_reference_limepy(name):
    """alpha_j, rho_j/sigma_j shapes, concentration, and r_h match the cached
    canonical-LIMEPY model at the frozen (measured-first) gates."""
    cfg = CASES[name]
    ref = _load_reference(name)
    assert bool(ref["converged"]), f"{name}: cached reference model not converged"
    model = _build_ours(cfg)

    r0, rt_ref = float(ref["r0"]), float(ref["rt"])
    xi_ref = ref["r"] / r0
    sel = (xi_ref > 0.0) & (xi_ref < 0.999 * rt_ref / r0)
    xi = jnp.asarray(xi_ref[sel])

    rho_ours, sig_ours = _ours_profiles(model, xi)
    rho_ref = ref["rhoj"][:, sel] / ref["rhoj"][:, 0:1]
    sig_ref = np.sqrt(ref["v2j"][:, sel] / ref["v2j"][:, 0:1])

    gates = cfg["gates"]
    d_rho = float(jnp.max(jnp.abs(rho_ours - jnp.asarray(rho_ref))))
    assert d_rho < gates["rho"], f"{name}: max|drho_j| = {d_rho:.2e}"
    d_sig = float(jnp.max(jnp.abs(sig_ours - jnp.asarray(sig_ref))))
    assert d_sig < gates["sig"], f"{name}: max|dsigma_j| = {d_sig:.2e}"

    d_alpha = float(np.max(np.abs(np.asarray(model.alpha_j) - ref["alpha"])))
    assert d_alpha < gates["alpha"], f"{name}: max|dalpha_j| = {d_alpha:.2e}"

    c_ours = float(jnp.log10(model.r_t / model.r_c))
    d_c = abs(c_ours - np.log10(rt_ref / r0))
    assert d_c < gates["c"], f"{name}: |dlog10(rt/r0)| = {d_c:.2e}"

    # r_h from OUR cumulative mass profile vs the reference's .rh
    xg = jnp.linspace(1e-5, float(model.r_t), 6000)
    rho_g, _ = _ours_profiles(model, xg)
    integ = jnp.sum(model.alpha_j[:, None] * rho_g, axis=0) * xg**2
    M = jnp.concatenate([jnp.zeros(1), jnp.cumsum(
        0.5 * (integ[1:] + integ[:-1]) * jnp.diff(xg))])
    rh_ours = float(jnp.interp(0.5 * M[-1], M, xg))
    rh_ref = float(ref["rh"]) / r0
    assert abs(rh_ours - rh_ref) / rh_ref < gates["rh"], \
        f"{name}: |drh|/rh = {abs(rh_ours - rh_ref) / rh_ref:.2e}"
